{{- range $key, $value := .Values.remote | default dict }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" $ }}-{{ $key }}
  namespace: {{ include "ns" $ }}
spec:
  type: ExternalName
  externalName: {{ $value }}
---
{{- end }}